#!/bin/sh
mknod -m 0666 /dev/null c 1 3
mknod -m 0660 /dev/ttyS0 c 4 64

mount -t proc proc /proc
mount -t sysfs sysfs /sys

ex=$(grep -o exercise-[0-9]* /proc/cmdline)
en=${ex#exercise-}

case "$en" in
	1|2|3|4)
		insmod /vuln-$en.ko
		mknod /dev/vuln c 60 1
		chmod a+rw /dev/vuln
		;;
	*)
		echo "unknown exercise: $ex"
		;;
esac

(
	HOME=/home/snh
	cd $HOME
	unset OLDPWD
	setsid cttyhack setuidgid 1000 sh
)


umount /proc
umount /sys

poweroff -f
